eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8888/eureka/
#### tomcat最大接线程数
server:
  port: 8765
  tomcat:
    max-threads: 50
spring:
  application:
    name: service-user-feign
feign:
   hystrix:
     enabled: true
 ###超时时间
hystrix:
   command:
     default:
       execution:
        isolation:
         thread:
          timeoutInMilliseconds: 4000
     

